### PR TITLE
aarch64 neon support for block-aligner

### PR DESCRIPTION
**Pull request by milot-mirdita**
This PR introduces neon support. There is still something weird going on with the blend instruction. However it doesn't seem to be causing issues in the alignment.

I lifted many of the instructions from SIMDe. Not sure where SIMDe should be credited.

### CODE REVIEW

**Comment by Daniel-Liu-c0deb0t** [comment]
Thanks for your contribution! I'm reviewing your changes and I'll probably push more changes to your branch. Let me know if that's not ok with you.

**Comment by milot-mirdita** [comment]
Sure, feel free to do anything with this :)

**Comment by Daniel-Liu-c0deb0t** [comment]
I've gone over the code quite carefully and simplified or fixed many of new neon code. The only remaining thing is I can't figure out why `blendv` doesn't work. At this point I think it might be an issue with the compiler.

**Comment by Daniel-Liu-c0deb0t** [comment]
I went through and simplified/fixed a lot of the code! I'll give it another pass later and merge it!

**Comment by Daniel-Liu-c0deb0t** [comment]
Once again, thanks for your contribution!

**Pull request merged**
